### ISSUE TITLE
Problems with unoconv and deployment outside of development environment

### ISSUE THREAD

**Issue by hudnash** [hudnash/phil#5]

**Comment by jackvaughan09** [comment]
Briefly looked into this and found a number of missing imports to run unoconv.py 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/50087612/208014541-e44060aa-5f1f-4d52-b5e9-58d2a6145a40.png">

Also some undefined variables? 
Haven't installed the packages yet, but will update if I do.

**Comment by jackvaughan09** [comment]
Closed.
